apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-central-station-deployment
  labels:
    app: base

spec:
  replicas: 1
  selector:
    matchLabels:
      app: base
  template:
    metadata:
      labels:
        app: base
    spec:
      volumes:
        - name: base-storage
          persistentVolumeClaim:
            claimName: archive-persistent-volume-claim
      containers:
        - name: base-central-station
          image: maiahmedhussein/central-base-deployment-image:latest
          volumeMounts:
            - name: base-storage
              mountPath: central-base/ParquetFiles
            - name: base-storage
              mountPath: central-base/src/main/java/test
